version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=strapi
      - POSTGRES_USER=strapi
      - POSTGRES_PASSWORD=strapi
    ports:
      - '5432:5432'
    volumes: 
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
  strapi:
    build:
      context: .
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
      - DATABASE_SCHEMA=strapi
      - PUBLIC_BASE_URL=http://localhost:8081
      - SERVER_SERVLET_CONTEXT_PATH=/entando-strapi
    ports:
      - '8081:8081'
    volumes:
      - ./volumes/strapi:/entando-data/entando-strapi